data <- read.csv("globalterrorismdb_0718dist.csv")
view(data)
head(data, 10)
dim(data)
library(dplyr)
glimpse(data)
summary(data)
library(DataExplorer)
DataExplorer::create_report(data)
data2 <- read.csv("gtd_lite.csv")
View(data2)
DataExplorer::create_report(data2)
